controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use app\models\Projects;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    private $u;
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function redirectNoUser()   //__contstruct() has the same problem
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect('site/login');
        }
    }

    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    public function actionError()
    {
        $this->redirectNoUser();

        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception]);
        }
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->redirectNoUser();
        $users = User::find()->all();
        $pr = Projects::find()->all();
        $titles = array('Id','Name','Title','Cost','Date start','Date end');
        $href = array('href' => '/site/user', 'title' => 'Add user');
        $script = 'scriptProj';
        return $this->render('index',array('user' => $users, 'proj' => $pr, 'items' => $titles, 'hrefs' =>$href ));
    }
    public function actionUser(){
        $this->redirectNoUser();
        $user = User::find()->all();
        $titles = array('Id','Fio','Login','Password');
        $href = array('href' => '/', 'title' => 'Add proj');
        $script = 'scriptProj';
        return $this->render('user',array('user' => $user, 'items' => $titles, 'hrefs' =>$href ));
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goHome();
        } 
        return $this->render('login', [
            'model' => $model,
        ]);

    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $this->redirectNoUser();

        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $this->redirectNoUser();

        return $this->render('about');
    }
    private function isAjax(){
        $this->redirectNoUser();

    }
    public function actionEditfield()
    {
        $this->redirectNoUser();
        $id = Yii::$app->request->post('id');
        $pr = Projects::findOne($id);
        $this->u = new Projects;
        $this->changeUserData(Yii::$app->request->post());
        $this->u->save();
    }
    public function actionCreatefield()
    {
        $this->redirectNoUser();
        $this->u = new Projects;
        $this->changeUserData(Yii::$app->request->post());
        if($this->u->save()){
            $user = User::find()->all();
            return $this->renderPartial('tr', array('p'=>$this->u, 'user' => $user));
        }
    }
    public function actionDeletefield()
    {
        $this->redirectNoUser();
        $id = Yii::$app->request->post('id');
        $pr = Projects::findOne($id);
        $pr->delete();
    }
    public function actionEdituser()
    {
        $this->redirectNoUser();
        $id = Yii::$app->request->post('id');
        $this->u = User::findOne($id);
        $this->changeUserData(Yii::$app->request->post());
        $this->u->save();
    }
    public function actionCreateuser()
    {
        $this->redirectNoUser();
        $this->u = new User;
        $this->changeUserData(Yii::$app->request->post());
        if($this->u->save()){
            return $this->renderPartial('tr_user', array('u'=>$this->u));
        }
    }
    private function changeUserData($post){
        foreach($post as $k => $v){
            $this->u->{$k}= $v;
        }
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Welcome!';
?>

<table>
    <thead>
        <tr>
            <?foreach($items as $i){?>
                <td><?=$i?></td>
            <?}?>
            <td style='cursor:pointer; background-color: #0fbf0f;'><a href="<?=$hrefs['href']?>"><?=$hrefs['title']?></a></td>
        </tr>
    </thead>
    <tbody>
        <?foreach($proj as $p){?>
            <?= $this->render('tr', array('p'=>$p, 'user' => $user)); ?>
        <?}?>
        <tr id='insert'>
            <form id='form_create'>
                <td>New item</td>
                <td>
                    <select name="uid">
                        <?foreach($user as $u){?>
                            <option value="<?=$u->id?>"><?=$u->fio?></option>
                        <?}?>
                    </select>
                </td>
                <td><input type="text" name='title'></td>
                <td><input type="number" step="any" name='cost'></td>
                <td><input type="date" name='date_start'></td>
                <td><input type="date" name='date_end'></td>
                <td><div class='create btn'>Add item</div></td>
            </form>
        </tr>
    </tbody>
</table>


<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'></script>

<script type="text/javascript">
$('.update').click(function() {
    var formData = $('#form_'+$(this).attr('field_id')).serialize();
    $.ajax({
        url: 'site/editfield',
        data: formData,
        type: 'POST',
        complete: function (data) {
            console.log(data.responseText);
        }
    });
})
$('.delete').click(function() {
    var id = $(this).attr('field_id');
    $.ajax({
        url: 'site/deletefield',
        data: {id : id},
        type: 'POST',
        complete: function (data) {
            $('#tr_'+id).remove();
        }
    });
})
$('.create').click(function() {
    var formData = $('#form_create').serialize();
    $.ajax({
        url: 'site/createfield',
        data: formData,
        type: 'POST',
        complete: function (data) {
            $('#insert').before(data.responseText);
            $("#form_create")[0].reset();
        }
    });
})
</script>

<style>
a{color: white;}
a:hover{color: white;}
table{
    width: 100%;
}
table select{
    width: 100%;
}
td{
    width: 14.2%;
}
thead td{
    text-align: center;
    border-right: 1px solid #ecf0f5;
    padding: 10px 0;
    background-color: #3c8dbc;
    color: #ecf0f5;
}
table .btn{
    text-align: center;
    padding: 10px 0;
    border-radius: 5px;
    transition: ease .1s all;
    width: 45%;
}
table .update{
    background-color: #3c8dbc;
    color: #ecf0f5;
}
table .delete{
    background-color: #222d32;
    color: #ecf0f5;
    float: right;
}
table .create{
    width: 100%;
    background-color: #3c8dbc;
    color: #ecf0f5;
}
.delete:hover{
    color: red;
}
.update:hover{
    background-color: #0fbf0f;
    color: #ecf0f5;
}
.create:hover{
    background-color: #0fbf0f;
    color: #ecf0f5;
}
tbody td{
    padding: 10px;
}
.id_field{
    width: 100%;
    background: transparent;
    border: none;
}
tbody tr:nth-child(2n){
    background-color: #e3e6ea;
}
</style>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/tr.php
<tr id='tr_<?=$p->id?>'>
     <form action="" id='form_<?=$p->id?>'>
         <td><input type="text" name='id' value='<?=$p->id?>' readonly class='id_field'></td>
         <td>
             <select name="uid">
                 <?foreach($user as $u){?>
                     <option value="<?=$u->id?>" <?=($u->id == $p->uid) ? 'selected' : ''?>><?=$u->fio?></option>
                 <?}?>
             </select>
         </td>
         <td><input type="text" name='title' value='<?=$p->title?>'></td>
         <td><input type="number"  step="any" name='cost' value='<?=$p->cost?>'></td>
         <td><input type="date" name='date_start' value='<?=$p->date_start?>'></td>
         <td><input type="date" name='date_end' value='<?=$p->date_end?>'></td>
         <td><div class='update btn' field_id='<?=$p->id?>'>Update</div> <div class='delete btn' field_id='<?=$p->id?>'>Delete</div></td>
     </form>
 </tr>

views/site/tr_user.php
<tr id='tr_<?=$u->id?>'>
     <form action="" id='form_<?=$u->id?>'>
         <td><input type="text" name='id' value='<?=$u->id?>' readonly class='id_field'></td>
         <td><input type="text" name='fio' value='<?=$u->fio?>'></td>
         <td><input type="login" name='date_start' value='<?=$u->login?>'></td>
         <td><input type="password" name='date_end' value='<?=$u->password?>'></td>
         <td><div class='update btn' field_id='<?=$u->id?>'>Update</div></td>
     </form>
 </tr>

views/site/user.php
<?php

/* @var $this yii\web\View */

$this->title = 'Edit user';
?>

<table>
    <thead>
        <tr>
            <?foreach($items as $i){?>
                <td><?=$i?></td>
            <?}?>
            <td style='cursor:pointer; background-color: #0fbf0f;'><a href="<?=$hrefs['href']?>"><?=$hrefs['title']?></a></td>
        </tr>
    </thead>
    <tbody>
        <?foreach($user as $u){?>
            <?= $this->render('tr_user', array('u' => $u)); ?>
        <?}?>
        <tr id='insert'>
            <form id='form_create'>
                <td>New user</td>
                <td><input type="text" name='fio' ></td>
                <td><input type="login" name='login' ></td>
                <td><input type="password" name='password' ></td>
                <td><div class='create btn'>Add user</div></td>
            </form>
        </tr>
    </tbody>
</table>


<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'></script>

<script type="text/javascript">
$('.update').click(function() {
    var formData = $('#form_'+$(this).attr('field_id')).serialize();
    $.ajax({
        url: '/site/edituser',
        data: formData,
        type: 'POST',
        complete: function (data) {
            console.log(data.responseText);
        }
    });
})
$('.create').click(function() {
    var formData = $('#form_create').serialize();
    $.ajax({
        url: '/site/createuser',
        data: formData,
        type: 'POST',
        complete: function (data) {
            $('#insert').before(data.responseText);
            $("#form_create")[0].reset();
        }
    });
})
</script>

<style>

a{color: white;}
a:hover{color: white;}
table{
    width: 100%;
}
table select{
    width: 100%;
}
table td{
    width: 20%;
}
thead td{
    text-align: center;
    border-right: 1px solid #ecf0f5;
    padding: 10px 0;
    background-color: #3c8dbc;
    color: #ecf0f5;
}
table .btn{
    text-align: center;
    padding: 10px 0;
    border-radius: 5px;
    transition: ease .1s all;
    width: 100%;
}
table .update{
    background-color: #3c8dbc;
    color: #ecf0f5;
}
table .create{
    width: 100%;
    background-color: #3c8dbc;
    color: #ecf0f5;
}
table .delete:hover{
    color: red;
}
table .update:hover{
    background-color: #0fbf0f;
    color: #ecf0f5;
}
.create:hover{
    background-color: #0fbf0f;
    color: #ecf0f5;
}
table tbody td{
    padding: 10px;
}
table .id_field{
    width: 100%;
    background: transparent;
    border: none;
}
tbody tr:nth-child(2n){
    background-color: #e3e6ea;
}
</style>